#!/bin/sh
# Emit a tmux chrome snippet (status bar, window tabs, pane borders, popups)
# for one of the tmux-design themes. Writes to STDOUT only.
#
#   tmux_theme.sh <theme> [--nerd]        print the snippet
#   tmux_theme.sh --list                  list theme names
#
# Apply it without touching the user's config:
#   tmux_theme.sh nord > ~/.config/tmux/theme.tmux
#   tmux source-file ~/.config/tmux/theme.tmux
#
# This never edits ~/.tmux.conf. A theme the user cannot undo is worse than no
# theme at all, so the "install" step stays an explicit source-file they own.
#
# The role values below are copied verbatim from THEMES in renderer_template.py,
# in that file's role vocabulary — bg/surface are its banner_bg/sel_bg. Panes and
# chrome must resolve a role to the same hex or a themed pane ends up sitting in
# a differently-themed status bar. If you edit one file, regenerate the other.

set -eu

# ---- argument parsing (flags may appear before or after the theme name) ----
THEME=""
NERD=0
for arg in "$@"; do
    case "$arg" in
        --nerd) NERD=1 ;;
        --list) THEME="--list" ;;
        -*) echo "unknown flag: $arg" >&2; exit 1 ;;
        *) [ -z "$THEME" ] && THEME="$arg" ;;
    esac
done

# role fields, in order:
#   banner_bg sel_bg title head text muted dim border ok warn err hot accent
theme_def() {
    case "$1" in
    catppuccin-mocha)
        echo "#181825 #313244 #f5c2e7 #89b4fa #cdd6f4 #a6adc8 #6c7086 #45475a #a6e3a1 #f9e2af #f38ba8 #fab387 #cba6f7" ;;
    catppuccin-latte)
        echo "#e6e9ef #ccd0da #ea76cb #1e66f5 #4c4f69 #6c6f85 #9ca0b0 #bcc0cc #40a02b #df8e1d #d20f39 #fe640b #8839ef" ;;
    tokyo-night)
        echo "#16161e #283457 #bb9af7 #7aa2f7 #c0caf5 #a9b1d6 #565f89 #3b4261 #9ece6a #e0af68 #f7768e #ff9e64 #7dcfff" ;;
    nord)
        echo "#2e3440 #3b4252 #b48ead #81a1c1 #eceff4 #d8dee9 #4c566a #434c5e #a3be8c #ebcb8b #bf616a #d08770 #88c0d0" ;;
    gruvbox-dark)
        echo "#282828 #3c3836 #d3869b #83a598 #ebdbb2 #bdae93 #928374 #504945 #b8bb26 #fabd2f #fb4934 #fe8019 #8ec07c" ;;
    rose-pine)
        echo "#1f1d2e #26233a #c4a7e7 #9ccfd8 #e0def4 #908caa #6e6a86 #403d52 #9ccfd8 #f6c177 #eb6f92 #ebbcba #31748f" ;;
    # The legacy palette is attribute-based for text/muted/dim/border (plain `2`,
    # i.e. dim). tmux styles need concrete colors, so those four are the closest
    # 256 approximations; the six hued roles are the renderer's exact indices.
    ansi256-legacy)
        echo "colour236 colour238 colour212 colour117 colour252 colour245 colour240 colour240 colour114 colour221 colour203 colour208 colour212" ;;
    *) return 1 ;;
    esac
}

THEMES="catppuccin-mocha catppuccin-latte tokyo-night nord gruvbox-dark rose-pine ansi256-legacy"

if [ "$THEME" = "--list" ]; then
    for t in $THEMES; do echo "$t"; done
    exit 0
fi

if [ -z "$THEME" ] || ! def="$(theme_def "$THEME")"; then
    echo "usage: tmux_theme.sh <theme> [--nerd]" >&2
    echo "themes: $THEMES" >&2
    exit 1
fi

# `set -- $def` would collapse to one argument under zsh, which does not word-split
# unquoted expansions. `read` behaves identically in sh, bash, dash and zsh.
IFS=' ' read -r BG SURFACE TITLE HEAD TEXT MUTED DIM BORDER OK WARN ERR HOT ACCENT <<EOF
$def
EOF

# Separators. Powerline glyphs (U+E0B0-E0B2) live in the Private Use Area and
# need a Nerd Font; a missing glyph renders as tofu, a blank, or a double-width
# box depending on the terminal, and cannot be detected from the output. So plain
# Unicode is the default and --nerd is an explicit opt-in.
# Written as octal UTF-8 escapes so the bytes survive any editor or transport.
if [ "$NERD" = "1" ]; then
    SEP_R=$(printf '\356\202\260')        # U+E0B0 right hard divider
    SEP_R_SOFT=$(printf '\356\202\261')   # U+E0B1 right soft divider
    SEP_L=$(printf '\356\202\262')        # U+E0B2 left hard divider
else
    SEP_R=""                              # color change alone is the separator
    SEP_R_SOFT="│"
    SEP_L=""
fi

cat <<EOF
# ── tmux-design chrome · theme: $THEME ────────────────────────────────────
# Generated by tmux_theme.sh. Load with:  tmux source-file <this file>
# Role values mirror renderer_template.py exactly, so panes and chrome agree.

# Truecolor. Without terminal-features tmux quantizes every #rrggbb below to
# the 256 palette — tmux auto-detects only a handful of terminals, and neither
# VS Code nor Alacritty is among them.
set -g  default-terminal "tmux-256color"
set -ga terminal-features ",xterm-256color:RGB"
set -ga terminal-features ",alacritty:RGB"
set -ga terminal-features ",*-256color:RGB"

# ── status bar ───────────────────────────────────────────────────────────
set -g status on
set -g status-position bottom
set -g status-justify left
set -g status-interval 5
# The defaults are 10 and 40; anything richer silently truncates without these.
set -g status-left-length 100
set -g status-right-length 120
set -g status-style "bg=$BG,fg=$TEXT"

# Separator fg = the segment being left, bg = the segment being entered.
# The prefix indicator uses the 'hot' role — it is the one transient "pay
# attention now" state the chrome has, which is exactly what hot means in panes.
set -g status-left "\
#[fg=$BG,bg=#{?client_prefix,$HOT,$ACCENT},bold] #{?client_prefix,▶ ,}#S \
#[fg=#{?client_prefix,$HOT,$ACCENT},bg=$SURFACE,nobold]$SEP_R\
#[fg=$TEXT,bg=$SURFACE] #{b:pane_current_path} \
#[fg=$SURFACE,bg=$BG]$SEP_R"

# Background windows that want attention. Activity is a neutral-good "something
# happened" signal; a bell is an error-grade interrupt, so they take 'ok' and
# 'err' respectively rather than both being a generic highlight.
set -g window-status-activity-style "fg=$OK,bg=$BG"
set -g window-status-bell-style     "fg=$BG,bg=$ERR,bold"

set -g window-status-separator ""
set -g window-status-format "\
#[fg=$DIM,bg=$BG]  #I $SEP_R_SOFT #W#{?window_flags,#{window_flags}, } "
# The active tab uses 'head', not 'ok' — the current window is an identity, not
# a success state, and reserving green for real health keeps color meaningful.
set -g window-status-current-format "\
#[fg=$BG,bg=$HEAD]$SEP_R\
#[fg=$BG,bg=$HEAD,bold] #I $SEP_R_SOFT #W#{?window_zoomed_flag, [Z],} \
#[fg=$HEAD,bg=$BG,nobold]$SEP_R"

set -g status-right "\
#[fg=$SURFACE,bg=$BG]$SEP_L\
#[fg=$MUTED,bg=$SURFACE] #{session_windows}w #{window_panes}p \
#[fg=$ACCENT,bg=$SURFACE]$SEP_L\
#[fg=$BG,bg=$ACCENT,bold] %H:%M \
#[fg=$TITLE,bg=$ACCENT]$SEP_L\
#[fg=$BG,bg=$TITLE,bold] #h "

# A git branch on the right, cached so the status bar never blocks. #() never
# waits — it reuses the previous result — so run the real work out of band:
#   */2 * * * * cd ~/repo && git branch --show-current > /tmp/tmux-branch
# set -ga status-right "#[fg=$MUTED,bg=$BG] #(cat /tmp/tmux-branch 2>/dev/null) "

# ── messages, modes, popups ──────────────────────────────────────────────
set -g message-style         "bg=$WARN,fg=$BG"
set -g message-command-style "bg=$SURFACE,fg=$TEXT"
set -g mode-style            "bg=$SURFACE,fg=$TEXT"
set -g popup-style           "bg=$BG,fg=$TEXT"
set -g popup-border-style    "fg=$ACCENT"
set -g popup-border-lines    rounded

# ── pane borders ─────────────────────────────────────────────────────────
# Note: tmux ignores attributes (bold/italics) in border styles — fg/bg only.
set -g pane-border-status top
set -g pane-border-lines  single
set -g pane-border-indicators both
set -g pane-border-style        "fg=$BORDER"
set -g pane-active-border-style "#{?pane_in_mode,fg=$WARN,#{?pane_synchronized,fg=$ERR,fg=$ACCENT}}"

# Inside a conditional, ',' and '}' must be escaped as '#,' and '#}'.
set -g pane-border-format "\
#{?pane_active,#[fg=$BG#,bg=$ACCENT#,bold],#[fg=$MUTED#,bg=$SURFACE]} \
#{pane_index} #{?#{@label},#{@label},#{pane_current_command}} \
#{?pane_active,#[fg=$ACCENT#,bg=default#,nobold],#[fg=$SURFACE#,bg=default]}$SEP_R"

# Per-pane labels:  tmux set -p -t <pane> @label "api logs"
# Tell renderers in this session which palette to use, so panes match this chrome:
setenv -g TMUX_DESIGN_THEME "$THEME"
EOF
